### ISSUE TITLE
Error on hex BN convert

### ISSUE THREAD

**Issue by Sigri44** [drlecks/Simple-Web3-Php#10]
Hello,

I don't know how to BN is converted, but result from smart contract is different (int256). Don't have the same result :
<img width="268" alt="image" src="https://user-images.githubusercontent.com/9304947/193632549-56df8458-908e-43ad-b1e1-ff9bb163886f.png">

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/9304947/193632609-aadfd61b-fb53-4021-8570-5340554c0c73.png">

Debug code is :
```php
gettype($res) :
string(6) "object"

$res :
object(stdClass)#129 (1) { ["result"]=> object(phpseclib\Math\BigInteger)#128 (2) { ["value"]=> string(22) "0x88fc3778e02d105c0000" ["engine"]=> string(3) "gmp" } }

gettype($res->result) :
string(6) "object"

$res->result :
object(phpseclib\Math\BigInteger)#128 (2) { ["value"]=> string(22) "0x88fc3778e02d105c0000" ["engine"]=> string(3) "gmp" }

$sweb3->utils->isHex("0x89056739d164b5e90000") :
bool(true)

$sweb3->utils->hexToBn("0x89056739d164b5e90000") :
object(phpseclib\Math\BigInteger)#202 (2) { ["value"]=> string(24) "0x0089056739d164b5e90000" ["engine"]=> string(3) "gmp" }

$sweb3->utils->fromWei($res->result, "ether") :
array(2) { [0]=> object(phpseclib\Math\BigInteger)#130 (2) { ["value"]=> string(8) "0xf76c91" ["engine"]=> string(3) "gmp" } [1]=> object(phpseclib\Math\BigInteger)#204 (2) { ["value"]=> string(18) "0x084f3304b81c0000" ["engine"]=> string(3) "gmp" } }

$sweb3->utils->toEther($res->result, "wei" :
array(2) { [0]=> object(phpseclib\Math\BigInteger)#130 (2) { ["value"]=> string(8) "0xf76c91" ["engine"]=> string(3) "gmp" } [1]=> object(phpseclib\Math\BigInteger)#202 (2) { ["value"]=> string(18) "0x084f3304b81c0000" ["engine"]=> string(3) "gmp" } } -562031.4012466292
```

**Comment by drlecks** [comment]
Hi, 

Big numbers are true pain. Doesn't handle decimals. When transforming to bigger units, where divisions can produce decimals, big number returns an array of [quotient, remainder], not a "simple" big number.

Transforming toEther and fromWei is very delicate for this reason. That's why I added the xxxString versions, that return a "human readable" amount. All math involving BigNumbers has to be done in weis. Transformation to bigger units are only for user's I/O.

As for your example: 

`40432342326000000000000` transforms to `0x88FD777A5C42D216000` in hex ([online hex converter](https://www.rapidtables.com/convert/number/decimal-to-hex.html))

This code:
``` PHP
$bn1 = Utils::hexToBn("0x88FD777A5C42D216000");  
echo $bn1 . " ";
echo Utils::fromWeiToString($bn1, "ether") . " "; 
echo Utils::toEtherString($bn1, "wei") . " ";
```

Prints as expected:
`40432342326000000000000 40432.342326000000000000 40432.342326000000000000
`

**Comment by Sigri44** [comment]
Thanks for the clarification but I think that's not exactly the point.

When I use the explorer, the contract tells me :
`int256: 40371499598000000000000`
Which is the real expected answer.

But when I call from SWeb3 the contract, the raw answer given is :
`0x88c8b1adb02476ae0000`

Which would give us according to your conversion table :
`645943993568000000000000`

By doing `$sweb3->utils->hexToBn("0x88c8b1adb02476ae0000")`, I get :
`0x0088c8b1adb02476ae0000`

Which would also give us according to your conversion table:
`645943993568000000000000`

Concerning the toString function :
`Fatal error: Uncaught Error: Call to undefined method SWeb3\Utils::toEtherString()`
(Have 0.9 version from composer, not dev branch)

So I don't understand how to find the expected result, indeed I want to find the same value as int256 from the retrieved GN, not the other way around.

**Comment by drlecks** [comment]
Ok, 

Then the problem is at the decoding step of the call function.

Can you paste here an example contract where this happens? I would help a lot. 

Btw, I'm testing it on the main-dev branch. It has some improvements in the ABI decoder... So the example code can help me to find the problem.

**Comment by Sigri44** [comment]
> Ok,
> 
> Then the problem is at the decoding step of the call function.
> 
> Can you paste here an example contract where this happens? I would help a lot.
> 
> Btw, I'm testing it on the main-dev branch. It has some improvements in the ABI decoder... So the example code can help me to find the problem.

`https://optimistic.etherscan.io/address/0x82ac2CE43e33683c58BE4cDc40975E73aA50f459#readProxyContract#F3`
