### ISSUE TITLE
合约解析 数组元组模式出现错误

### ISSUE THREAD

**Issue by Y-J-L** [drlecks/Simple-Web3-Php#12]
例如下面的abi
"name": "getPairs",
"outputs": [
{
"components": [
{
"internalType": "uint256",
"name": "pairId",
"type": "uint256"
},
{
"internalType": "address",
"name": "pancakePair",
"type": "address"
},
{
"internalType": "address",
"name": "token0",
"type": "address"
},
{
"internalType": "address",
"name": "token1",
"type": "address"
},
{
"internalType": "uint256",
"name": "balance0",
"type": "uint256"
},
{
"internalType": "uint256",
"name": "balance1",
"type": "uint256"
},
{
"internalType": "uint256",
"name": "decimals0",
"type": "uint256"
},
{
"internalType": "uint256",
"name": "decimals1",
"type": "uint256"
}
],
"internalType": "struct GetPairs.pairInfo[]",
"name": "",
"type": "tuple[]"
}
],
"stateMutability": "view",
"type": "function"

正常应该返回类似下面的数据
![image](https://user-images.githubusercontent.com/23184737/200498427-5f209757-3516-4d06-98f9-05dc9ed6d260.png)

使用该sdk返回的是
![image](https://user-images.githubusercontent.com/23184737/200498547-c3a491f3-6a59-4b01-87ec-744618dc3caa.png)

看起来像是DecodeInput_UInt_Internal计算错误

**Comment by drlecks** [comment]
It seems related with #5 . Some questions:

- Witch branch are you seeing this behaviour? Only main branch has this issue fixed (fixed-length tuple parameters). 
- If on the main branch. Can you share connection data to test the call? (network endpoint, network chainid, contract address, valid parameters?)

**Comment by drlecks** [comment]
I've just tried your code, and it looks like the info is correct.

Are you sure you are on the main branch and not on the v0.9? Chech your composer.json file, it should contain something like `"drlecks/simple-web3-php": "dev-master"`. I will publish a v0.10 version soon, as it has some important changes with tupple and large negative numbers decoding.

This is the result I got:
![image](https://user-images.githubusercontent.com/3506116/200800604-32934c91-2ac8-4f38-97d3-02291255e0dc.png)

Note : ints are formated as BigIntegers. You should convert the values to string before encoding them as json. 
`$bigInt->toString()` should be enough. In the examples, I'm using `PrintCallResult($res)` to "pretty-print" the return values, you can check there.

**Comment by Y-J-L** [comment]
> I've just tried your code, and it looks like the info is correct.
> 
> Are you sure you are on the main branch and not on the v0.9? Chech your composer.json file, it should contain something like `"drlecks/simple-web3-php": "dev-master"`. I will publish a v0.10 version soon, as it has some important changes with tupple and large negative numbers decoding.
> 
> This is the result I got: ![image](https://user-images.githubusercontent.com/3506116/200800604-32934c91-2ac8-4f38-97d3-02291255e0dc.png)
> 
> Note : ints are formated as BigIntegers. You should convert the values to string before encoding them as json. `$bigInt->toString()` should be enough. In the examples, I'm using `PrintCallResult($res)` to "pretty-print" the return values, you can check there.

抱歉，我的是在0.9.0的版本，我更改一下试试，谢谢
