### ISSUE TITLE
请问有 使用 eth.subscribe的方法吗？

### ISSUE THREAD

**Issue by Y-J-L** [drlecks/Simple-Web3-Php#13]
有没有方法可以监听交易吗？就像是web3js的eth.subscribe

**Comment by drlecks** [comment]
There isn't this option **yet**. 

Subscription has more sense in a client environment where the state persists during time. However in PHP that is not so useful.

If you need some sort of logs reader, you could make a cron and use the `getLogs` function with a block-number range. Something like this:

```PHP
$start_block = getLastBlockFromDataBase();  // -> int
$end_block = $start_block + 25;

$logs = $tokenContract->getLogs( '0x'.dechex($start_block), '0x'.dechex($end_block) );

foreach ($logs as $log) {
 ....
}

saveLastBlockToDatabase($end_block);
```

NOTE: You should also check the end block not to be higher than the latest block on the blockchain. And if it does, replace the last argument from getLogs to 'latest'.
