### ISSUE TITLE
ERROR: estimateGas error: execution reverted: Ownable: caller is not an owner

### ISSUE THREAD

**Issue by giny21** [drlecks/Simple-Web3-Php#17]
Hello
I'm so glad that you created this library, it makes communication with smart-contracts easier.
I'm working on NFT solution on Polygon chain and I have problem with sending data to my smart-contract. I understand from error message that it's about owner address but I have no idea how to set this address correct in $contract->send function call.

PHP code:
```
        $web3 = new SWeb3(
            $setting->getNetworkUrl()
        );

        $web3->setPersonalData(
            $setting->getWalletAddress(),
            $setting->getWalletPrivateKey()
        );
        $web3->chainId = 0x13881; //mumbai
        $contract = new SWeb3_Contract(
            $web3,
            $setting->getArtifactsContractAddress(),
            json_encode($setting->getArtifactsContractAbi())
        );

        $contract->send(
            'addArtifact',
            [
                $itemId, //int
                $transaction->getInProviderId(), //string
                $setting->getArtifactBaseUrl()."/".$itemId, //string
                base64_encode(json_encode($itemJsonArray)), //string
                $sender, //address
            ]
        );
```

And smart-contract function:
```
    function addArtifact(uint256 tokenId, uint256 transactionId, string memory uri, string memory tokenData, address to)
        public onlyOwner
    {
        _mint(to, tokenId);

        _setTokenURI(tokenId, uri);
        _tokenDatas[tokenId] = tokenData;

        delete _waitingTransactions[transactionId];
        
        emit Minted(tokenId);
    }
```
Any help will be appricieted

**Comment by drlecks** [comment]
Without the ownable implementation (Solidity), I can just guess. But here are some thoughts:

- Usually, the owner is set auto when you deploy the contract. It's the address that "pays/executes" the deployment. 
- You can change the ownership manually too.
- You can query the current owner with a getter (maybe getOwner() or just the owner property).
- The `onlyOwner` modifier is internally => `require(msg.sender == owner);`. So the only requisite is that the sender is the current contract owner. 

If `addArtifact()` is `public onlyOwner`, it must be sent and signed by the same account that owns the contract (so normally, the deployer address). That means that **only the owner of the contract can add artifacts**. Then, `$setting->getWalletAddress()` and `$setting->getWalletPrivateKey()` must provide the same owner address and it's related private key.

**Comment by giny21** [comment]
I solved it like 15 minutes after posting issue but I decide to let it be for future readers.
So my smart contract, as you assumed, store address of owner (I use modifier from openZeppelin). For some reason ```$contract->send``` didn' add ```from``` value so I did that manually in extraData field and it worked.
Full, working code:
```
$web3 = new SWeb3(
            $setting->getNetworkUrl()
        );

        $web3->setPersonalData(
            $setting->getWalletAddress(),
            $setting->getWalletPrivateKey()
        );
        $web3->chainId = 0x13881;
        $contract = new SWeb3_Contract(
            $web3,
            $setting->getArtifactsContractAddress(),
            json_encode($setting ->getArtifactsContractAbi())
        );

        $result = $contract->send(
            'addArtifact',
            [
                $playableGearItemId,
                $transaction->getInProviderId(),
                $setting->getArtifactBaseUrl()."/".$playableGearItemId,
                base64_encode(json_encode($playableGearItemArray)),
                $sender,
            ],
            [
                "from" => $setting->getWalletAddress(),
                "nonce" => $web3->personal->getNonce()
            ]
        );
```

**Comment by drlecks** [comment]
I suppose you are using the 0.9 release code. On the main branch there is a line added on `SWeb3_Contract->send()` that overrides the `$extra_params['from']` value with `$this->sweb3->personal->address;` (where `$this` is the `SWeb3_Contract` instance).

I suggest you to switch to the main branch until I publish a new release as it has many improvements in function calling and ABI encoding/decoding. 

PS: It's weird that the EVM doesn't get the `msg.sender` automatically from the request signature. At least, I hope it validates it with the signature, otherwise it may lead to critical security issues.
