### ISSUE TITLE
error when call $result = $sweb3->send($sendParams);

### ISSUE THREAD

**Issue by phanvantri09** [drlecks/Simple-Web3-Php#19]
Call to undefined function Mdanter\Ecc\Curves\gmp_init()
![image](https://user-images.githubusercontent.com/72957574/209981429-befdf008-470b-4c63-8fb9-0316dd064177.png)

**Comment by drlecks** [comment]
You need to enable `gmp`  in your server. 

GMP is instaled by default in php. Be sure you have the extension enabled in your php.ini.

If it's not instaled, just apt install php-gmp
