### ISSUE TITLE
countryBlocked!

### ISSUE THREAD

**Issue by nimobn** [drlecks/Simple-Web3-Php#20]
hi. i am getting this error when i call send method of library. what should i do? 

{
    "error": "countryBlocked",
    "message": "This service is not available in your country"
}

**Comment by drlecks** [comment]
Hi!

Your endpoint provider may not be available in your country. 

Check this link:
https://www.vice.com/en/article/g5qkb7/ethereum-companies-suddenly-ban-users-in-certain-countries

You can try another provider.
