### ISSUE TITLE
Send array parameters

### ISSUE THREAD

**Issue by paulgotea** [drlecks/Simple-Web3-Php#21]
I'm trying to make a call to this contract where getAmountsOut method requires 2 parameters. One uint256 and address[].

I can't make it work because I don't know how I need to call the function and pass the parameters to make it work. 

P.S.: It's working while trying to call a method that requires only parameters uint256. I have issues while passing [].

<img width="769" alt="Screenshot 2023-01-24 at 13 43 01" src="https://user-images.githubusercontent.com/8556874/214283071-a7a7b587-6db6-4c80-bd35-c1c0b05e5622.png">

Appreciate!

Also check it out https://stackoverflow.com/questions/75219723/web3-php-contract-call for a better explanation using WEB3 PHP

**Comment by drlecks** [comment]
Hi!

You must wrap all parameters inside an array. Also Etherscan may accept a simple "address" when should be an "address array", but here the value must match the type.

```php
$res = $contract->call('getAmountsOut', [ '12341234', ['0x1234....1234'] ] ); // ('getAmountsOut', [ uint256, address[] ] )
```
