### ISSUE TITLE
Attemps to read property "inputs" on null

### ISSUE THREAD

**Issue by ahmed-laggoun** [drlecks/Simple-Web3-Php#26]
in this line:
`$result = $contract->deployContract( [123123],  $extra_params); `

i got error: Attemps to read property "inputs" on null

it was because my contract doesn't have a constructor, so you should handle the case when the compiled contract doesn't have a constructor.

**Comment by drlecks** [comment]
Pushed a fix.

FYI, if you are deploying a contract with no parameters, you should call `$result = $contract->deployContract( [],  $extra_params); `. First parameter as an empty array.

**Comment by ahmed-laggoun** [comment]
It didn't work too, because there's no constructor in abi so it means: 
`$this->ABI->constructor = null`
