### ISSUE TITLE
\drlecks\simple-web3-php\Core\ABI.php:272 Error type

### ISSUE THREAD

**Issue by webnatrix** [drlecks/Simple-Web3-Php#27]
Приветствую, есть вот такая ошибка.

`{#1527 ▼ // vendor\drlecks\simple-web3-php\Core\ABI.php:272
  +"type": "bytes32"
}`
Line 271 -  $var_name = $input->name;

![Без имени](https://user-images.githubusercontent.com/35181081/218929511-e45d1ff5-d14c-484d-9175-77e7ba38c833.png)

Пытается взять name но дает type

$line = ABI::EncodeParameters_External(['bytes32', 'address', 'address', 'uint256'], ['0xc0d4a6ac8f8fb36bff3758bb7eaad7f9ce4f649ace74192d64d0625c1b7e0943', 'asd', 'asdasd', 10]);

**Comment by webnatrix** [comment]
Исправьте на 
`$var_name = $input->type;` Line 271

**Comment by drlecks** [comment]
Hi, 

This is a fixed bug on the main branch. There, the line 271 is replaced with:

`$var_name = is_object($input) ? $input->name : $input;`

**Comment by webnatrix** [comment]
![image](https://user-images.githubusercontent.com/35181081/219020621-607b382f-61cc-49ba-a3bf-cae549ea24cc.png)
Смотрите он не может взять name так как указан type

**Comment by webnatrix** [comment]
![asdasdasd](https://user-images.githubusercontent.com/35181081/219020835-b96f9fab-0d6f-469e-95ad-71f272fa6751.png)
Вот из пакета ошибка выскакивает

**Comment by webnatrix** [comment]
Hi
`
public static function EncodeParameters_External(array $input_types, array $data) : string
    { 
		$inputs = array();
		foreach($input_types as $it) {
			$input = new stdClass();
			$input->type = $it;
			$inputs []= $input;
		}
 
        return '0x' . self::EncodeGroup($inputs, $data);
    }
`

Line `$input->type = $it;`

But here he tries to take the name

` public static function EncodeGroup(array $inputs, array $data) : string
    { 
        $hashData = "";
        $currentDynamicIndex = count($inputs) * self::NUM_ZEROS / 2; 
        
        //parameters
        $i = 0; 
        foreach ($inputs as $pos => $input) 
        {     

            $var_name = $input->type;
            $inputData = is_object($data) ? $data->$var_name : $data[$pos];  
            if (is_array($data) && $inputData == null) $inputData = $data[$var_name];

            $hashData .= self::EncodeInput($input, $inputData, 1, $currentDynamicIndex); 
  
            if(isset($input->hash)) $currentDynamicIndex += strlen($input->hash) / 2;
            $i++;
        }

        foreach($inputs as $pos => $input) { 
            $hashData .= self::EncodeInput($input, null, 2, $currentDynamicIndex); 
        }

        if (count($inputs) == 0) {
            $hashData .= self::NUM_ZEROS / 2;
        } 
 
        return $hashData;
    }`

Line  ` $var_name = $input->type;`

**Comment by webnatrix** [comment]
Hi
[https://github.com/drlecks/Simple-Web3-Php/blob/master/Core/ABI.php#L298](url)

Gives the variable type "type"

[https://github.com/drlecks/Simple-Web3-Php/blob/master/Core/ABI.php#L271](url)

Accepts the type "name"

**Comment by drlecks** [comment]
Yes, `$var_name` won't be used if coming from `EncodeParameters_External`, but still trying to read an undefined property.
