### ISSUE TITLE
Signature is not correct for a complex contract

### ISSUE THREAD

**Issue by cryptogs75** [drlecks/Simple-Web3-Php#30]
Hello,
I have used the Opensea contract at 0x00000000006c3852cbEf3e08E8dF289169EdE581 and got the ABI from here. I have tried to check the signature of the function fulfillBasicOrder(), which is quite complex :
$abi->Init($opensea_abi);
$function = $abi->GetFunction('fulfillBasicOrder');
$data = $abi->GetSignatureFromEvent($function);

I get : 0xaf84e809e6076db3ce2cb7f5da51cfda86a4f3e774067fcbb34d23c187460303.

When checking the trace of a call made to this function, I can see that the prefix should be 0xfb0f3ee1 while I got 0xaf84e809 in my example.

Any clue why ?

Thanks and regards,
Mosi

**Comment by drlecks** [comment]
This function has a tuple[] input type. It was indeed not checked on the function hash method!

**Comment by cryptogs75** [comment]
Awesome ! Thanks a lot !
