### ISSUE TITLE
Can't send ETH to addresses starting with "0x0"

### ISSUE THREAD

**Issue by sonofliberty** [drlecks/Simple-Web3-Php#33]
This code trims the address and removes all leading zeros, making it impossible to send ETH to addresses starting with `0x0`:

Web3p\RLP\Types\Str:42
```php
if (mb_strlen($input) > 2) {
  $input = ltrim($input, '0');
}
```

The exception:
`transaction could not be decoded: could not decode RLP components: could not decode list item 3 to Address: invalid address: 0x93...`

The address in question begins with 0x0093.

**Comment by drlecks** [comment]
Hi, 

`Web3p\RLP` is an external repo.

First of all, you should open an issue there for further info and a possible fix.

I'm using a slightly older version of `Web3p\RLP\Types\Str.php`  that does not have just that if section, and just works fine. You should have some extra caution when sending hex values, and check that they don't have leading zeros.

**Comment by sonofliberty** [comment]
Hi,

Since the functioning of your library depends on it, I thought this is the right place to open an issue. I've also noticed web3p/rlp already has an unresolved issue about the same topic.

Please let me know what version of web3p/rlp you are using.

Thanks.

**Comment by drlecks** [comment]
As `rpl` is a sub dependency of `ethereum-offline-raw-tx`, I'm not sure that you can force using a valid version (3.4). One solution would be to manually to delete the if statement at `rlp/src/Types/Str.php:41`

```php
if (mb_strlen($input) > 2) {
      $input = ltrim($input, '0');
}
```

Note that this is a temporal/bad solution as `composer update` would wipe it out.

PD: If you find a way to configure our library's composer.json to force using rlp version 3.4, I'll be happy to add it or merge a pull request ;)
