### ISSUE TITLE
Tuple Singature different ..

### ISSUE THREAD

**Issue by HydraCoderX** [drlecks/Simple-Web3-Php#34]
Hi, i did what you were saying in my other Issue, and now at least the function gets called,  but it fails, as the sent datas are wrong.  The hash i am sending is completly different to what i would send in a real  or even if i am using abi https://abi.hashex.org/   

is there any way to contact you to send you over some details to look at it? i did read everything but i cant find any idea why this is happening. 

its only because of that tuple.. ^^ 

thx

**Comment by HydraCoderX** [comment]
ok i was able to solve that myself, seems the ABI.php does not support an array of tuples, added that, and now it works fine

**Comment by drlecks** [comment]
Hi!

You were experiencing the problem with all arrays of tuples? 
Tuples had only fixed length types or variable too?
Can you share the fix you found, may be a good contribution!

Thanks!

BTW, we have a gitter channel for less "formal" communication. Check the readme for the link.
