### ISSUE TITLE
2 Bugs in encoding tuples ( Incorrect assumption that tuple is always dynamic ) ?

### ISSUE THREAD

**Issue by slawomir-pryczek** [drlecks/Simple-Web3-Php#36]
I think i came across an error for encoding tuples. First in EncodeInput, it will always put tuple's content at the end of currently constructed data block using $input->hash. For non-dynamic parameters it should be put in-place as far as i understand the specs so that's the first error which will prevent correctly encoding some tuples.

In EncodeGroup
$currentDynamicIndex = count($inputs) * self::NUM_ZEROS / 2;
This is probably not correct as well as single tuple can have several non-dynamic fields only, eg. 3 UINTs, so the assumption that first dynamic 32b data block starts at position which is just a number of inputs is not always correct (we need to process all tuples before we know first dynamic block number).

Just getting to know this code, so please let me know if that makes sense.

As far as i understand how it forks currently:
Currently for non-dynamic tuples the code incorrectly moves dynamic index forward by number of non-dynamic tuples and then it incorrectly places the tuple content at the end. It should move the dynamic index by number of non-dynamic tuples elements. Eg. if you have 2 non-dynamic tuples with 4 elements each the dynamic index will be moved by 2 positions, instead of 2x4, and data of these tuples will be placed at the end.

**Comment by drlecks** [comment]
Hi, thanks for the feedback!

> First in EncodeInput, it will always put tuple's content at the end of currently constructed data block using $input->hash. For non-dynamic parameters it should be put in-place as far as i understand the specs so that's the first error which will prevent correctly encoding some tuples.

Check the $round parameter on EncodeInput(). Static types ignore round=2 and attach the encoded value directly on first round, as you say.

> In EncodeGroup
$currentDynamicIndex = count($inputs) * self::NUM_ZEROS / 2;
This is probably not correct as well as single tuple can have several non-dynamic fields only, eg. 3 UINTs, so the assumption that first dynamic 32b data block starts at position which is just a number of inputs is not always correct (we need to process all tuples before we know first dynamic block number).

Yes, you are right. One of the latest commits fixes the same issue, but on the "decode" process. 

Throught experimentation, we saw that a  tuple with only static attribute types behave like a static type itself. So, it's not encoded using a offset index, it just encodes all its parameters in place. I haven't been able to find any docs with info about this "feature"... If you find it, I will be pleased to check it and make sure our code adjusts to the docs. 

August is complicated... But I'll update it as soon as possible.

Make sure you are on main branch for most recent changes.

**Comment by slawomir-pryczek** [comment]
Hey, thanks for the message... for decoding yes seems to work 100% correct. As for first point i think there's an issue with this code (the issue is here only for tuple)

```
else if ($varType == VariableType::Tuple) {
  $input->hash =  self::EncodeGroup($input->components, $inputData);

  $res =  '';
  if (self::ExistsDynamicParameter($input->components)) {
	$res = self::EncodeInput_UInt($currentDynamicIndex); 
  }
                 
  return $res;
```

So what i think it does is it'll always put the tuple content as last data in the block ( $input->hash ). If content is dynamic it'll also put an offset in-place.

It should work this way (i think)

```
$res = self::EncodeGroup($input->components, $inputData);
				
				// if the tuple is dynamic, we return offset and add tuple's data at the end
				if (self::ExistsDynamicParameter($input->components)) {
					$input->hash = $res;
					return self::EncodeInput_UInt($currentDynamicIndex);
				}
				return $res;
```
So for static it'll return $res in-place, and for dynamic it'll return offset and put data in input->hash to be added in phase 2.


>Throught experimentation, we saw that a tuple with only static attribute types behave like a static type itself.
Yes, correct... if all attribs are static the tuple is treated as static type. Attached the structure desc at the bottom...

Will prepare a fix and submit tomorrow i think, need to test it more wanted to make sure it won't break other things but it seems ok, just need to encode/decode more contract parameters, unless there's some test suite...

```[inputs] => Array
                (
                    [0] => Array
                        (
                            [internalType] => address[]
                            [name] => path
                            [type] => address[]
                        )

                    [1] => Array
                        (
                            [internalType] => string[]
                            [name] => poolVersion
                            [type] => string[]
                        )

                    [2] => Array
                        (
                            [internalType] => uint256[]
                            [name] => versionLen
                            [type] => uint256[]
                        )

                    [3] => Array
                        (
                            [internalType] => uint24[]
                            [name] => fees
                            [type] => uint24[]
                        )

                    [4] => Array
                        (
                            [components] => Array
                                (
                                    [0] => Array
                                        (
                                            [internalType] => uint256
                                            [name] => amountIn
                                            [type] => uint256
                                        )

                                    [1] => Array
                                        (
                                            [internalType] => uint256
                                            [name] => amountOutMin
                                            [type] => uint256
                                        )

                                    [2] => Array
                                        (
                                            [internalType] => address
                                            [name] => to
                                            [type] => address
                                        )

                                    [3] => Array
                                        (
                                            [internalType] => uint256
                                            [name] => deadline
                                            [type] => uint256
                                        )

                                )

                            [internalType] => struct SmartExchangeRouter.SwapData
                            [name] => data
                            [type] => tuple
                        )

                )```

**Comment by slawomir-pryczek** [comment]
https://github.com/drlecks/Simple-Web3-Php/pull/39
