### ISSUE TITLE
substr(): Argument #3 ($length) must be of type ?int, float given

### ISSUE THREAD

**Issue by skritku** [drlecks/Simple-Web3-Php#40]
`$contract->getLogs();`

fails with:

```
 at vendor/drlecks/simple-web3-php/Core/ABI.php:893
    889▕     {
    890▕         $length = self::DecodeInput_UInt_Internal($encoded, $start);
    891▕         $start += self::NUM_ZEROS;
    892▕ 
  ➜ 893▕         $partial = substr($encoded, $start, $length * 2);
    894▕         return hex2bin($partial);
    895▕     }
    896▕ 
    897▕ 
```

Actual for both 0.10 and master

**Comment by drlecks** [comment]
Hi!

I am testing it with the example contract defined on the Examples folder and can't reproduce the problem.

You can see it if you execute this on the polygon testnet Mumbai:
```PHP
//initialize SWeb3 main object
$sweb3 = new SWeb3('https://rpc-mumbai.maticvigil.com', []);
 
//initialize contract from address and ABI string
$contract = new SWeb3_contract($sweb3, '0xB4b2E069327577e3b6822052B0c3Ad8311C1A7Aa', SWP_Contract_ABI); 

//EVENTS
$res = $contract->getLogs('0x2584FD8', '0x2584FDF');

//function defined on ./Example/example.call.php
PrintCallResult('getLogs', $res);
```

If your problem persists, it would be great to have a reproducible environment, like the one I just pasted:
- Net connection data (If it's mumbai-polygon, better)
- Contract ABI
- Contract address
- Event block number interval, to reliably find events.

**Comment by skritku** [comment]
Hi! 
I'm testing on localhost (truffle + ganache).
Found that problem exists only when decoding events with non-ASCII strings:

`MyEvent(_from: address, _msg: string)`

Not so critical for me.

**Comment by skritku** [comment]
Ah, problem was not in non-ASCII symbols. 

`event MyEvent(address indexed _from, string **indexed** _msg);`

Removed 'indexed' and that solved the problem. 
My bad, sorry.
