### ISSUE TITLE
The output data of the read contract command is missing [solved]

### ISSUE THREAD

**Issue by quyunet** [drlecks/Simple-Web3-Php#44]
The output data of the read contract command is missing, actually there is a lot of data in _dataContract, but many values in the current code output data are missing.

```php
namespace SWeb3;
require 'vendor/autoload.php'; 

use SWeb3\SWeb3;            //always needed, to create the Web3 object
use SWeb3\Utils;           //sweb3 helper classes (for example, hex conversion operations)
use SWeb3\SWeb3_Contract;  //contract creation and interaction
use SWeb3\Accounts;        //account creation
use SWeb3\Account;         //single account management (signing)
use phpseclib\Math\BigInteger as BigNumber;		//BigInt handling
use stdClass;             //for object interaction 

//initialize SWeb3 main object
$sweb3 = new SWeb3('https://bsc-dataseed1.defibit.io/');

// Contract ABI
$contractABI = '[{"inputs":[{"internalType":"address","name":"_user","type":"address"}],"name":"contractInfo","outputs":[{"components":[{"internalType":"uint256","name":"time","type":"uint256"},{"internalType":"uint256","name":"launched","type":"uint256"},{"internalType":"uint256","name":"balance","type":"uint256"},{"internalType":"uint256","name":"minDeposit","type":"uint256"},{"internalType":"uint256","name":"agg_invested","type":"uint256"},{"internalType":"uint256","name":"ht_invested","type":"uint256"},{"internalType":"uint256","name":"ht_refReward","type":"uint256"},{"internalType":"uint256","name":"ht_earned","type":"uint256"},{"internalType":"uint256","name":"ht_withdrawn","type":"uint256"},{"internalType":"uint256","name":"ht_lottery","type":"uint256"},{"internalType":"uint256","name":"insBalance","type":"uint256"},{"internalType":"uint256","name":"ht_insSentAgg","type":"uint256"},{"internalType":"uint256","name":"ht_insRecvAgg","type":"uint256"},{"internalType":"uint256","name":"avgBalance","type":"uint256"},{"internalType":"uint256","name":"weekIndex","type":"uint256"},{"internalType":"uint256","name":"wk_refReward","type":"uint256"},{"internalType":"uint256","name":"weekEndsIn","type":"uint256"},{"components":[{"internalType":"address","name":"user","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"internalType":"struct TRUEFUND_V2.Deposit[10]","name":"topDeposits","type":"tuple[10]"},{"components":[{"internalType":"address","name":"user","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"internalType":"struct TRUEFUND_V2.Deposit[10]","name":"topReferrers","type":"tuple[10]"},{"components":[{"internalType":"enum TRUEFUND_V2.Flags","name":"flag","type":"uint8"},{"internalType":"uint256","name":"time","type":"uint256"},{"internalType":"uint256","name":"amt1","type":"uint256"},{"internalType":"uint256","name":"amt2","type":"uint256"},{"internalType":"uint256","name":"amt3","type":"uint256"},{"internalType":"address","name":"addr1","type":"address"},{"internalType":"address","name":"addr2","type":"address"}],"internalType":"struct TRUEFUND_V2.History[20]","name":"history","type":"tuple[20]"},{"components":[{"internalType":"uint256","name":"bank","type":"uint256"},{"internalType":"uint256","name":"ticketsCount","type":"uint256"},{"internalType":"uint256","name":"usersCount","type":"uint256"},{"internalType":"uint256","name":"winnerTicket","type":"uint256"},{"internalType":"address","name":"winnerUser","type":"address"},{"internalType":"uint256","name":"maxUsers","type":"uint256"},{"internalType":"uint256","name":"percent","type":"uint256"},{"internalType":"uint256","name":"price","type":"uint256"},{"internalType":"uint256","name":"prize","type":"uint256"}],"internalType":"struct TRUEFUND_V2.LotteryInfo","name":"lotteryPrev","type":"tuple"},{"components":[{"internalType":"uint256","name":"bank","type":"uint256"},{"internalType":"uint256","name":"ticketsCount","type":"uint256"},{"internalType":"uint256","name":"usersCount","type":"uint256"},{"internalType":"uint256","name":"winnerTicket","type":"uint256"},{"internalType":"address","name":"winnerUser","type":"address"},{"internalType":"uint256","name":"maxUsers","type":"uint256"},{"internalType":"uint256","name":"percent","type":"uint256"},{"internalType":"uint256","name":"price","type":"uint256"},{"internalType":"uint256","name":"prize","type":"uint256"}],"internalType":"struct TRUEFUND_V2.LotteryInfo","name":"lotteryCurr","type":"tuple"},{"components":[{"internalType":"uint256","name":"finished","type":"uint256"},{"internalType":"address","name":"winner","type":"address"},{"internalType":"uint256","name":"bank","type":"uint256"},{"internalType":"uint256","name":"prize","type":"uint256"}],"internalType":"struct TRUEFUND_V2.LotteryResult[20]","name":"lotteryResults","type":"tuple[20]"}],"internalType":"struct TRUEFUND_V2.DataContract","name":"_dataContract","type":"tuple"},{"components":[{"internalType":"uint256","name":"balance","type":"uint256"},{"internalType":"uint256","name":"allowance","type":"uint256"}],"internalType":"struct TRUEFUND_V2.DataUser","name":"_dataUser","type":"tuple"}],"stateMutability":"view","type":"function"}]';

$contractAddress = '0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F';

$contract = new SWeb3_contract($sweb3, $contractAddress, $contractABI);
$walletAddress = '0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F';

$callName = 'contractInfo';
$result = $contract->call($callName, $walletAddress);
PrintCallResult($callName, $result);     // output result

function PrintCallResult($callName, $result)
{
    echo "<br/> Call -> <b>". $callName . "</b><br/>";

    echo "Result -> " . PrintObject($result) . "<br/>"; 
}

function PrintObject($x)
{ 
	if ($x instanceof BigNumber)
	{
		return $x . '';
	}
	
	if (is_object($x)) {
		$x = (array)($x); 
	}

	if (is_array($x))
	{
		$text = "[";
		$first = true;
		foreach($x as $key => $value)
		{
			if ($first)  	$first = false;
			else 			$text .= ", ";

			$text .= $key . " : " . PrintObject($value);
		}

		return $text . "]"; 
	}
	 
	return $x . '';
}
```
how to solve this issue?

**Comment by drlecks** [comment]
So, this giga-call still has secrets to discover!

ABI was not detecting if 2nd level tuples were static to guess the data offset. With this commit there is more data displayed.

Just tell me if the data is correct or if there is still something wrong! This is a 19K character output data to decode. Almost a record for sure!

**Comment by quyunet** [comment]
> So, this giga-call still has secrets to discover!
> 
> ABI was not detecting if 2nd level tuples were static to guess the data offset. With this commit there is more data displayed.
> 
> Just tell me if the data is correct or if there is still something wrong! This is a 19K character output data to decode. Almost a record for sure!

It should not be as large as 18K of data. You can directly browse the block and input the address for testing
[https://bscscan.com/address/0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F#readContract#F36](https://bscscan.com/address/0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F#readContract#F36)

**Comment by drlecks** [comment]
Yes, the decoded data that you see there is about 5K characters long. The encoded hexa string that the jsonRPC returns is much more long. I was just joking about the complexity of your contract ;)

Just check the output now. If you think they are correct, you can close this issue.

**Comment by lucas-quinn-guru** [comment]
I think I'm having a similar issue.

`
namespace SWeb3;

ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');

include_once("vendor/autoload.php");

use SWeb3\SWeb3;
use SWeb3\SWeb3_Contract;
use phpseclib\Math\BigInteger as BigNumber;

$SWP_Contract_ABI = '[{"inputs":[{"internalType":"bool","name":"onSale","type":"bool"},{"internalType":"uint256","name":"_startIndex","type":"uint256"},{"internalType":"uint256","name":"_endIndex","type":"uint256"}],"name":"getTokenINFO","outputs":[{"components":[{"internalType":"uint256","name":"mintingTimestamp","type":"uint256" },{"internalType":"uint256","name":"claimableRewards","type":"uint256"},{"internalType":"uint256","name":"tokenNo","type":"uint256"},{"internalType":"uint256","name":"activePoolSize","type":"uint256"},{"internalType":"uint256","name":"pendingPoolSize","type":"uint256"},{"internalType":"uint256","name":"salePoolSize","type":"uint256"},{"internalType":"enum WarfiContract.TokenTiers","name":"tier","type":"uint8"},{"internalType":"uint256","name":"mode","type":"uint256"}],"internalType":"struct WarfiContract.tokenDetails[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"}]';
$extra_curl_params = [];

//initialize SWeb3 main object
$sweb3 = new SWeb3("https://rpc.ankr.com/polygon", $extra_curl_params);

//initialize contract from address and ABI string
$contract = new SWeb3_contract($sweb3, "0xfD35B1EecD6C2fA2Ba9b72D6204FF84bE750c89C", $SWP_Contract_ABI);

//GETTERS - direct public variables
$res = $contract->call('getTokenINFO', [0, 1, 300]);
PrintCallResult('getTokenINFO', $res);

exit(0);

function PrintCallResult($callName, $result)
{
    echo PHP_EOL . " Call -> --" . $callName . "--" . PHP_EOL;

    echo "Result -> " . PrintObject($result) . PHP_EOL;
}

function PrintObject($x, $tabs = 0)
{
    if ($x instanceof BigNumber) {
        return $x;
    }

    if (is_object($x)) {
        $x = (array)($x);
    }

    if (is_array($x)) {
        $text = "[";
        $first = true;
        foreach ($x as $key => $value) {
            if ($first) {
                $first = false;
            } else {
                $text .= ", ";
            }

            $text .= PHP_EOL . str_pad("", $tabs * 5, " ") . $key . " : " . PrintObject($value, $tabs + 1);
        }

        return $text . PHP_EOL . str_pad("", ($tabs - 1) * 5, " ") . "]";
    }

    return $x . '';
}
`

> The above code is meant to be run at the root of the project on command line at the same level as the vendor directory.
> 
> I can run this on two different machines.  1 with recent dev-master branch.  1 on dev-master branch from August 21, 2023.  This code works as expected on dev-master from August 21, but does not work as expected on recent dev-master.

Expected Result: 

`Call -> --getTokenINFO--
Result -> [
array_1 : [
     0 : [
          mintingTimestamp : 1683268569, 
          claimableRewards : 0, 
          tokenNo : 1, 
          activePoolSize : xxxxxxxxxxxxx, 
          pendingPoolSize : 0, 
          salePoolSize : 0, 
          tier : 1, 
          mode : 2
     ], 
     1 : [
          mintingTimestamp : 1683268583, 
          claimableRewards : 187266762143579367226, 
          tokenNo : 2, 
          activePoolSize : xxxxxxxxxxxxx, 
          pendingPoolSize : 0, 
          salePoolSize : 0, 
          tier : 2, 
          mode : 0
     ], 
     ......... 
     299 : [
          mintingTimestamp : 1683272210, 
          claimableRewards : 0, 
          tokenNo : 300, 
          activePoolSize : xxxxxxxxxxxxx, 
          pendingPoolSize : 0, 
          salePoolSize : 0, 
          tier : 6, 
          mode : 2
     ]
]
]
`

Actual result

`Call -> --getTokenINFO--
Result -> [
array_1 : [
     0 : [
          mintingTimestamp : 300, 
          claimableRewards : 1683268569, 
          tokenNo : 0, 
          activePoolSize : 1, 
          pendingPoolSize : xxxxxxxxxxxx, 
          salePoolSize : 0, 
          tier : 0, 
          mode : 1
     ], 
     1 : [
          mintingTimestamp : 300, 
          claimableRewards : 1683268569, 
          tokenNo : 0, 
          activePoolSize : 1, 
          pendingPoolSize : xxxxxxxxxxxx, 
          salePoolSize : 0, 
          tier : 0, 
          mode : 1
     ], 
     .......
     31 : [
          mintingTimestamp : 300, 
          claimableRewards : 1683268569, 
          tokenNo : 0, 
          activePoolSize : 1, 
          pendingPoolSize : xxxxxxxxxxxx, 
          salePoolSize : 0, 
          tier : 0, 
          mode : 1
     ]
]
]    
`

When comparing the two result sets, element number 1 in the result set that works is displayed as the result set of the 32 elements that doesn't work and is off by 1 element. 

> Bad

`
 0 : [
          mintingTimestamp : 300, 
          claimableRewards : 1683268569, 
          tokenNo : 0, 
          activePoolSize : 1, 
          pendingPoolSize : xxxxxxxxxxxx, 
          salePoolSize : 0, 
          tier : 0, 
          mode : 1
     ], 
   `  

 > Good

  0 : [
          mintingTimestamp : 1683268569, 
          claimableRewards : 0, 
          tokenNo : 1, 
          activePoolSize : xxxxxxxxxxxxx, 
          pendingPoolSize : 0, 
          salePoolSize : 0, 
          tier : 1, 
          mode : 2
     ], 
`

**Comment by lucas-quinn-guru** [comment]
> I think I'm having a similar issue.
> 
> ```
> namespace SWeb3;
> 
> ini_set('display_errors', '1');
> ini_set('display_startup_errors', '1');
> 
> include_once("vendor/autoload.php");
> 
> use SWeb3\SWeb3;
> use SWeb3\SWeb3_Contract;
> use phpseclib\Math\BigInteger as BigNumber;
> 
> $SWP_Contract_ABI = '[{"inputs":[{"internalType":"bool","name":"onSale","type":"bool"},{"internalType":"uint256","name":"_startIndex","type":"uint256"},{"internalType":"uint256","name":"_endIndex","type":"uint256"}],"name":"getTokenINFO","outputs":[{"components":[{"internalType":"uint256","name":"mintingTimestamp","type":"uint256" },{"internalType":"uint256","name":"claimableRewards","type":"uint256"},{"internalType":"uint256","name":"tokenNo","type":"uint256"},{"internalType":"uint256","name":"activePoolSize","type":"uint256"},{"internalType":"uint256","name":"pendingPoolSize","type":"uint256"},{"internalType":"uint256","name":"salePoolSize","type":"uint256"},{"internalType":"enum WarfiContract.TokenTiers","name":"tier","type":"uint8"},{"internalType":"uint256","name":"mode","type":"uint256"}],"internalType":"struct WarfiContract.tokenDetails[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"}]';
> $extra_curl_params = [];
> 
> //initialize SWeb3 main object
> $sweb3 = new SWeb3("https://rpc.ankr.com/polygon", $extra_curl_params);
> 
> //initialize contract from address and ABI string
> $contract = new SWeb3_contract($sweb3, "0xfD35B1EecD6C2fA2Ba9b72D6204FF84bE750c89C", $SWP_Contract_ABI);
> 
> //GETTERS - direct public variables
> $res = $contract->call('getTokenINFO', [0, 1, 300]);
> PrintCallResult('getTokenINFO', $res);
> 
> exit(0);
> 
> function PrintCallResult($callName, $result)
> {
>     echo PHP_EOL . " Call -> --" . $callName . "--" . PHP_EOL;
> 
>     echo "Result -> " . PrintObject($result) . PHP_EOL;
> }
> 
> function PrintObject($x, $tabs = 0)
> {
>     if ($x instanceof BigNumber) {
>         return $x;
>     }
> 
>     if (is_object($x)) {
>         $x = (array)($x);
>     }
> 
>     if (is_array($x)) {
>         $text = "[";
>         $first = true;
>         foreach ($x as $key => $value) {
>             if ($first) {
>                 $first = false;
>             } else {
>                 $text .= ", ";
>             }
> 
>             $text .= PHP_EOL . str_pad("", $tabs * 5, " ") . $key . " : " . PrintObject($value, $tabs + 1);
>         }
> 
>         return $text . PHP_EOL . str_pad("", ($tabs - 1) * 5, " ") . "]";
>     }
> 
>     return $x . '';
> }
> ```
> 
> > The above code is meant to be run at the root of the project on command line at the same level as the vendor directory.
> > I can run this on two different machines.  1 with recent dev-master branch.  1 on dev-master branch from August 21, 2023.  This code works as expected on dev-master from August 21, but does not work as expected on recent dev-master.
> 
> Expected Result:
> 
> ```
> Result -> [
> array_1 : [
>      0 : [
>           mintingTimestamp : 1683268569, 
>           claimableRewards : 0, 
>           tokenNo : 1, 
>           activePoolSize : xxxxxxxxxxxxx, 
>           pendingPoolSize : 0, 
>           salePoolSize : 0, 
>           tier : 1, 
>           mode : 2
>      ], 
>      1 : [
>           mintingTimestamp : 1683268583, 
>           claimableRewards : 187266762143579367226, 
>           tokenNo : 2, 
>           activePoolSize : xxxxxxxxxxxxx, 
>           pendingPoolSize : 0, 
>           salePoolSize : 0, 
>           tier : 2, 
>           mode : 0
>      ], 
>      ......... 
>      299 : [
>           mintingTimestamp : 1683272210, 
>           claimableRewards : 0, 
>           tokenNo : 300, 
>           activePoolSize : xxxxxxxxxxxxx, 
>           pendingPoolSize : 0, 
>           salePoolSize : 0, 
>           tier : 6, 
>           mode : 2
>      ]
> ]
> ]
> ```
> 
> Actual result
> 
> ```
> Result -> [
> array_1 : [
>      0 : [
>           mintingTimestamp : 300, 
>           claimableRewards : 1683268569, 
>           tokenNo : 0, 
>           activePoolSize : 1, 
>           pendingPoolSize : xxxxxxxxxxxx, 
>           salePoolSize : 0, 
>           tier : 0, 
>           mode : 1
>      ], 
>      1 : [
>           mintingTimestamp : 300, 
>           claimableRewards : 1683268569, 
>           tokenNo : 0, 
>           activePoolSize : 1, 
>           pendingPoolSize : xxxxxxxxxxxx, 
>           salePoolSize : 0, 
>           tier : 0, 
>           mode : 1
>      ], 
>      .......
>      31 : [
>           mintingTimestamp : 300, 
>           claimableRewards : 1683268569, 
>           tokenNo : 0, 
>           activePoolSize : 1, 
>           pendingPoolSize : xxxxxxxxxxxx, 
>           salePoolSize : 0, 
>           tier : 0, 
>           mode : 1
>      ]
> ]
> ]    
> ```
> 
> When comparing the two result sets, element number 1 in the result set that works is displayed as the result set of the 32 elements that doesn't work and is off by 1 element.
> 
> > Bad
> 
> ```
>  0 : [
>           mintingTimestamp : 300, 
>           claimableRewards : 1683268569, 
>           tokenNo : 0, 
>           activePoolSize : 1, 
>           pendingPoolSize : xxxxxxxxxxxx, 
>           salePoolSize : 0, 
>           tier : 0, 
>           mode : 1
>      ], 
> ```
> 
> > Good
> 
> ```
>   0 : [
>           mintingTimestamp : 1683268569, 
>           claimableRewards : 0, 
>           tokenNo : 1, 
>           activePoolSize : xxxxxxxxxxxxx, 
>           pendingPoolSize : 0, 
>           salePoolSize : 0, 
>           tier : 1, 
>           mode : 2
>      ], 
> ```

The issue happens in the following code within core->abi->DecodeGroup(), but I'm not sure why.....I've added my comments to help debug....

```if(Utils::string_contains($output->type, '['))
            {
                echo "I'm an array" . PHP_EOL;
                $var_name 			= $output->name != '' ? $output->name : 'array_'.$array_count;

	        //arrays with all static parameters have no initial array offset
                $isStaticArray = self::IsStaticParameter($varType);
                if ($varType == VariableType::Tuple) {
                                          //got here
					$isStaticArray = !self::ExistsDynamicParameter($output->components);
                                          echo "isStaticArray: " . $isStaticArray . PHP_EOL; //prints to screen the number 1/true
                }
	        $dynamic_data_start = 0;
                if ($isStaticArray) $dynamic_data_start = $index;
                else 				$dynamic_data_start = $first_index + self::DecodeInput_UInt_Internal($encoded, $index) * 2;

                //uncommenting following line overrides conditional $isStaticArray conditional statement, but give expected results                
                //$dynamic_data_start = $first_index + self::DecodeInput_UInt_Internal($encoded, $index) * 2;

                echo "dynamic data start: " . $dynamic_data_start . PHP_EOL;
                $group->$var_name = self::DecodeInput_Array($output, $encoded, $dynamic_data_start);
                $array_count++;
            }```

**Comment by drlecks** [comment]
This issue is being harden than expected! 

Check now! @lucas-quinn-guru @quyunet

**Comment by lucas-quinn-guru** [comment]
> This issue is being harden than expected!
> 
> Check now! @lucas-quinn-guru @quyunet

Magical.  This is working as expected for me.  This project has been a total lifesaver for me.  Thank you so much.

**Comment by quyunet** [comment]
> This issue is being harden than expected!
> 
> Check now! @lucas-quinn-guru @quyunet

Thank you very much, The problem has been resolved.
