### ISSUE TITLE
can I get the Latest 25 BEP-20 Token Transfer Events on a specified contract through Simple-Web3-Php? 

### ISSUE THREAD

**Issue by quyunet** [drlecks/Simple-Web3-Php#45]
can I get the Latest 25 BEP-20 Token Transfer Events on a specified contract through Simple-Web3-Php?

by browse to view Latest 25 BEP-20 Token Transfer Events: [https://bscscan.com/address/0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F#tokentxns](https://bscscan.com/address/0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F#tokentxns)

How to get event records through "Simple-Web3-Php"? and how to get the number of start and end block?
[https://bscscan.com/block/32018276](https://bscscan.com/block/32018276)

```php
//initialize SWeb3 main object
$extra_curl_params = [
	CURLOPT_SSL_VERIFYPEER => false,
	CURLOPT_SSL_VERIFYHOST => false
];
$sweb3 = new SWeb3('https://rpc.ankr.com/bsc', $extra_curl_params);

$contractABI = '[]';
//initialize contract from address and ABI string
$contract = new SWeb3_contract($sweb3, '0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F', $contractABI); 

$last_block = '32018276';
$start_block = $last_block - 25;
//EVENTS
$res = $contract->getLogs(0x.$start_block, 0x .$last_block);

PrintCallResult('getLogs', $res);
```
but the above script cannot obtain data, taking the above contract as an example, how to get the number of start and end block?

**Comment by drlecks** [comment]
I don't think that json-RPC lets you retrieve the logs like this directly. Events are written on each block and you need to first get the blocks you want to check, and then search for the logs in them.  

So its not straightforward to search a specific number of events, or search events by date, for example. One solution for your problem, would be define a starting block (can be the latest block), and start searching logs backwards. 

SO, in this scenario, I would get the latest block, and read backwards the biggest possible blocks until I find 25 logs. Using this to get the latest 3000 blocks: 

```PHP
$last_block = $sweb3->call('eth_blockNumber', [])->result; 
$start_block = Utils::hexToBn($last_block)->add(new BigNumber(-3000));
$start_block = '0x'.Utils::toHex($start_block); 
```

Then I would iterate 3000 blocks by 3000 until my "25 event pool" is full. 
 
Note1: This technique can "consume" a lot of calls to the RPC endpoint. I would not use this approach if I'm paying a per call RPC provider like Infura or QuickNode, or if this feature will be very commonly used. You can set up a cron-job to save replicated event data on your server, to retrieve more easily this info, and avoid making iterative calls to your RPC endpoint. 

Note2: I've found that this endpoint has 3000 as the max block interval. Other endpoints have 1000, no limit... It depends on your provider. 

Note3: You can also filter events by event type using "topic filters". Optional 3rd argument on `SWeb3_contract::getLogs()`.  https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_newfilter

**Comment by quyunet** [comment]
> I don't think that json-RPC lets you retrieve the logs like this directly. Events are written on each block and you need to first get the blocks you want to check, and then search for the logs in them.
> 
> So its not straightforward to search a specific number of events, or search events by date, for example. One solution for your problem, would be define a starting block (can be the latest block), and start searching logs backwards.
> 
> SO, in this scenario, I would get the latest block, and read backwards the biggest possible blocks until I find 25 logs. Using this to get the latest 3000 blocks:
> 
> ```
> $last_block = $sweb3->call('eth_blockNumber', [])->result; 
> $start_block = Utils::hexToBn($last_block)->add(new BigNumber(-3000));
> $start_block = '0x'.Utils::toHex($start_block); 
> ```
> 
> Then I would iterate 3000 blocks by 3000 until my "25 event pool" is full.
> 
> Note1: This technique can "consume" a lot of calls to the RPC endpoint. I would not use this approach if I'm paying a per call RPC provider like Infura or QuickNode, or if this feature will be very commonly used. You can set up a cron-job to save replicated event data on your server, to retrieve more easily this info, and avoid making iterative calls to your RPC endpoint.
> 
> Note2: I've found that this endpoint has 3000 as the max block interval. Other endpoints have 1000, no limit... It depends on your provider.
> 
> Note3: You can also filter events by event type using "topic filters". Optional 3rd argument on `SWeb3_contract::getLogs()`. https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_newfilter

Thank you very much for your detailed answer and for the suggestions you provided!
