### ISSUE TITLE
how to call the interface functions of contract?

### ISSUE THREAD

**Issue by quyunet** [drlecks/Simple-Web3-Php#46]
how to call the interface functions of contract?

example contract code:
[https://bscscan.com/address/0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F#code](https://bscscan.com/address/0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F#code)

Can I call the "balanceOf" interface function?

**Comment by drlecks** [comment]
Check the example script at `Example/example.erc20.php`. There is exactly what are you searching for.
