### ISSUE TITLE
How to query the number of Token holdings on a specified contract? [Solved]

### ISSUE THREAD

**Issue by quyunet** [drlecks/Simple-Web3-Php#49]
How to query the number of Token holdings on a specified contract?

For example, viewed through a browser: [https://bscscan.com/tokenholdings?a=0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F](https://bscscan.com/tokenholdings?a=0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F)

**Comment by drlecks** [comment]
If it's an ERC20 contract, or similar. You have to call 'balanceOf'.

```php
$res = $contract->call('balanceOf', [$adress]);
```

**Comment by quyunet** [comment]
but the results cannot be obtained, why?

```php
$extra_curl_params = [
	CURLOPT_SSL_VERIFYPEER => false,
	CURLOPT_SSL_VERIFYHOST => false
];
$sweb3 = new SWeb3('https://rpc.ankr.com/bsc', $extra_curl_params);

$contractAddress = '0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F';
$stream_opts = [ "ssl" => [ "verify_peer"=>false, "verify_peer_name"=>false, ] ];
$bep20_abi = file_get_contents("https://raw.githubusercontent.com/bnb-chain/token-bind-tool/master/contracts/bep20/bep20.abi", false, stream_context_create($stream_opts));
$contract = new SWeb3_contract($sweb3, $contractAddress, $bep20_abi);
$res = $contract->call('balanceOf', [$contractAddress]);
```

response:
stdClass Object ( [jsonrpc] => 2.0 [id] => 1 [error] => stdClass Object ( [code] => -32000 [message] => execution reverted ) )

**Comment by drlecks** [comment]
Ok...

You are trying to query the balance of "token_a" owned by address 0x64...0f, witch is a contract. 

The error is conceptual. You have to declare the ERC20 contract on the address of the ERC20 contract. And then, ask for the balance of your own contract (0x64..0f). 

So, the RPC endpoint returns error because the 0x64...0f contract has no function called "balanceOf".

Just change this with the real ERC20 contract addrress and it should work: 
```PHP 
$contractAddress = '0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F'; 
```

**Comment by artman325** [comment]
I'll add my two cents

0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F - is a contract, but it doesn't impement IERC20(or tfIERC20 in the code)
Therefore, there are no 'balanceOf' methods available, which is why the transaction was reverted.

However, if we retrieve the address of the token held inside by calling the 'TOKEN' method, we can obtain the address of the BUSD stable token (0x55d398326f99059ff775485246999027b3197955). Now we can retrieve the 'balanceOf' for 0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F, for example. 
It could be implemented like this:
```php
$extra_curl_params = [
	CURLOPT_SSL_VERIFYPEER => false,
	CURLOPT_SSL_VERIFYHOST => false
];
$sweb3 = new SWeb3('https://rpc.ankr.com/bsc', $extra_curl_params);
$stream_opts = [ "ssl" => [ "verify_peer"=>false, "verify_peer_name"=>false, ] ];

$contract_abi = '[{"inputs":[],"name":"TOKEN","outputs":[{"internalType":"contract tfIERC20","name":"","type":"address"}],"stateMutability":"view","type":"function"}]';
$bep20_abi = file_get_contents("https://raw.githubusercontent.com/bnb-chain/token-bind-tool/master/contracts/bep20/bep20.abi", false, stream_context_create($stream_opts));

$contractAddress = '0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F';

$contract = new SWeb3_contract($sweb3, $contractAddress, $contract_abi);
$result = $contract->call('TOKEN', []);
$bep20Address = $result->result;
$bep20 = new SWeb3_contract($sweb3, $bep20Address, $bep20_abi);
$res = $bep20->call('balanceOf', [$contractAddress]);

print_r($res);
```

Here the answer of question "How much $contractAddress have BUSD?"

**Comment by quyunet** [comment]
```php
$contractAddress = '0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F';

$tokenContract = '0x55d398326f99059ff775485246999027b3197955';

$stream_opts = [ "ssl" => [ "verify_peer"=>false, "verify_peer_name"=>false, ] ];
$bep20_abi = file_get_contents("https://raw.githubusercontent.com/bnb-chain/token-bind-tool/master/contracts/bep20/bep20.abi", false, stream_context_create($stream_opts));

$contract = new SWeb3_contract($sweb3, $tokenContract, $bep20_abi);
$res = $contract->call('balanceOf', [$contractAddress]);
print_r($res);
```
Thank you for your reminder. After adding the code to the USDT contract, I obtained the following results:

stdClass Object ( [result] => phpseclib\Math\BigInteger Object ( [value] => 0x0cdfcfc51f2f3ec5e0e0 [engine] => gmp ) )

How to use the built-in method of Simple web3 to convert values to decimal?

**Comment by quyunet** [comment]
> I'll add my two cents
> 
> 0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F - is a contract, but it doesn't impement IERC20(or tfIERC20 in the code) Therefore, there are no 'balanceOf' methods available, which is why the transaction was reverted.
> 
> However, if we retrieve the address of the token held inside by calling the 'TOKEN' method, we can obtain the address of the BUSD stable token (0x55d398326f99059ff775485246999027b3197955). Now we can retrieve the 'balanceOf' for 0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F, for example. It could be implemented like this:
> 
> ```
> $extra_curl_params = [
> 	CURLOPT_SSL_VERIFYPEER => false,
> 	CURLOPT_SSL_VERIFYHOST => false
> ];
> $sweb3 = new SWeb3('https://rpc.ankr.com/bsc', $extra_curl_params);
> $stream_opts = [ "ssl" => [ "verify_peer"=>false, "verify_peer_name"=>false, ] ];
> 
> $contract_abi = '[{"inputs":[],"name":"TOKEN","outputs":[{"internalType":"contract tfIERC20","name":"","type":"address"}],"stateMutability":"view","type":"function"}]';
> $bep20_abi = file_get_contents("https://raw.githubusercontent.com/bnb-chain/token-bind-tool/master/contracts/bep20/bep20.abi", false, stream_context_create($stream_opts));
> 
> $contractAddress = '0x6485E794e03b12366c1607bDAA1581Dc3bd73F0F';
> 
> $contract = new SWeb3_contract($sweb3, $contractAddress, $contract_abi);
> $result = $contract->call('TOKEN', []);
> $bep20Address = $result->result;
> $bep20 = new SWeb3_contract($sweb3, $bep20Address, $bep20_abi);
> $res = $bep20->call('balanceOf', [$contractAddress]);
> 
> print_r($res);
> ```
> 
> Here the answer of question "How much $contractAddress have BUSD?"

How to query BNB BALANCE? The Token contract address for BNB is: 0xB8c77482e45F1F44dE1745F52C74426C631bDD52 ?

**Comment by drlecks** [comment]
The address you are sharing is a "wallet" address, not a contract. You can see it on the bsc scanner. 

If you want to query the BNB balance on the BNB Smart Chain, you want the native chain coin balance, so you must call eth_getBalance.

```php
$sweb3->call('eth_getBalance', [$address], 'latest');
```

**Comment by quyunet** [comment]
> The address you are sharing is a "wallet" address, not a contract. You can see it on the bsc scanner.
> 
> If you want to query the BNB balance on the BNB Smart Chain, you want the native chain coin balance, so you must call eth_getBalance.
> 
> ```
> $sweb3->call('eth_getBalance', [$address], 'latest');
> ```

thank you very much!
