### ISSUE TITLE
Stargate finance tuple issue

### ISSUE THREAD

**Issue by ironistdmi** [drlecks/Simple-Web3-Php#50]
https://bscscan.com/address/0x4a364f8c717cAAD9A442737Eb7b8A55cc6cf18D8#code

$contract = new SWeb3_contract($sweb3, '0x4a364f8c717cAAD9A442737Eb7b8A55cc6cf18D8', $StarGateRouterAbi); 
$callData = [109, 1, $wallet, "0x", ["dstGasForCall" => 0, "dstNativeAmount" => 0, "dstNativeAddr" => "0x"]];
$res = $contract->call('quoteLayerZeroFee', $callData);
PrintCallResult('quoteLayerZeroFee', $res);

error is
  Undefined array key 0
  at vendor/drlecks/simple-web3-php/Core/ABI.php:272

What i doing wrong?

P.S. also i try like this

$callData = [109, 1, $wallet, "0x", new stdClass()];
//tuple(uint256, string, string[])
$callData[4]->dstGasForCall = 0; 
$callData[4]->dstNativeAmount = 0; 
$callData[4]->dstNativeAddr = '0x'; 
$res = $contract->call('quoteLayerZeroFee', $callData);
PrintCallResult('quoteLayerZeroFee', $res);

another error like he want array instead object

**Comment by drlecks** [comment]
Hi there are 2 issues here:

1. You must format the last tuple input as a non idexed array [0, 0, '0x'].
2. There was a weird issue with "0x" when the type is bytes. I was considering it as a byte chain as it is not a valid hex representation. But it seems that the EVM handles this as a hex zero.
