### ISSUE TITLE
How to obtain correct bytes32 string?

### ISSUE THREAD

**Issue by itxtoledo** [drlecks/Simple-Web3-Php#53]
With var_dump im getting this:

```
 stdClass: object(stdClass)#209 (7) { ["elem_1"]=> string(16) "��gt+&�&��j%B)" ["elem_2"]=> string(16) "��gt+&�&��j%B)" ["elem_3"]=> string(16) "��gt+&�&��j%B)" ["elem_4"]=> string(16) "��gt+&�&��j%B)" ["elem_5"]=> string(16) "��gt+&�&��j%B)" ["elem_6"]=> object(phpseclib\Math\BigInteger)#213 (2) { ["value"]=> string(10) "0x6575156b" ["engine"]=> string(3) "gmp" } ["elem_7"]=> object(phpseclib\Math\BigInteger)#215 (2) { ["value"]=> string(10) "0x0145e1e6" ["engine"]=> string(3) "gmp" } }
```

How bytes32 string comes from this `0xdbe567742b26e60826fc0f8a6a25422900000000000000000000000000000000` to this `��gt+&�&��j%B)`

**Comment by itxtoledo** [comment]
apparently the library is missing the treatment for type `VariableType::BytesFixed`  in file "ABI.php" line 728

**Comment by drlecks** [comment]
Abi was already checking bytes32, on the "static types" decoding flow. But you were right, there was an issue with non hexa bytes32 data. Binary data was never encoded.
