### ISSUE TITLE
Error sending wallet address different from contract

### ISSUE THREAD

**Issue by tiendatmagic** [drlecks/Simple-Web3-Php#56]
How to send tokens via another wallet address with separate contract and ABI?

**Comment by drlecks** [comment]
I don't fully understand your problem. But if you look in the erc20 example (/Example/example.erc20.php), there is a functional example to send ERC20 tokens between addresses.

**Comment by tiendatmagic** [comment]
Is it possible to transfer coins using the SUI blockchain?

**Comment by drlecks** [comment]
It's the first time I hear about SUI. But, after a 5 min search, I doesn't look like a EVM RPC compatible chain (As Ethereum, Binance or Polygon). This library interacts with EthereumVirtualMachine nodes using jsonRPC calls.

So I assume the answer is no, you can't interact with the SUI blockchain at all.
