### ISSUE TITLE
unable to decode data via DecodeData method

### ISSUE THREAD

**Issue by tauseedzaman** [drlecks/Simple-Web3-Php#57]
HI am calling decodedata method of contract class.. gut not working

` dd($contract->DecodeData('transfer',$res->result->input));`

and its showing this

![image](https://github.com/drlecks/Simple-Web3-Php/assets/64689921/5bda5b57-0924-48d4-bd33-0e2642a7f10c)

this result->input is here
![image](https://github.com/drlecks/Simple-Web3-Php/assets/64689921/0df111f6-84ed-4b32-b628-1c9eb2486a81)

this same thing i am able to decode via online decoder [https://bia.is/tools/abi-decoder/](https://bia.is/tools/abi-decoder/)

![image](https://github.com/drlecks/Simple-Web3-Php/assets/64689921/483da203-4c88-497b-b361-878cecba422a)

am i doing something wrong or its a bug.. plz comment on this

**Comment by drlecks** [comment]
Hi!

What are you trying to achieve here? 

`ABI::DecodeData()` is used to decode return data (outputs) from a contract call.  You are passing input data to decode, and that will not work as you expect.

I can't imagine a use case where you want to decode the input data (as you already have that info, as you just made the call). But I assume you can decode the `$res->result->input` doing something like:

```PHP
$abi = new ABI();
$abi->Init("contract abi code");

$inputs = $abi->GetFunction('transfer')->inputs;
$data = $res->result->input;
$decoded = ABI::DecodeGroup($inputs , substr($data, 2), 0);
```

But as I said, in 99% of the cases, you shouldn't be calling manually to `$contract->DecodeData()` as this is implicitly done inside the `$contract->call()` function.
