### ISSUE TITLE
Core/ABI->GetEventFromHash throws exception on invalid index. 

### ISSUE THREAD

**Issue by lucas-quinn-guru** [drlecks/Simple-Web3-Php#58]
Currently, the GetEventFromHash is the following
   ```
public function GetEventFromHash($event_hash)
    {
            return $this->events_encoded[$event_hash];
    }

```

In other parts of code where this is called, from Contract, you're checking to see if(null) but the above will never return null.  It assumes that you have a valid ABI for every contract your are checking events from.  That's not always the case.  So, if the event is undefined by the contract ABI that I provide, shouldn't we return null?

```
public function GetEventFromHash($event_hash)
    {
        if( !empty( $this->events_encoded[$event_hash] ) ) {
            return $this->events_encoded[$event_hash];
        } else {
            return null;
        }
    }
```

My scenario is that I need to get all transfer events of unknown ERC20 contracts to track amounts transferred, but these unknown contracts could have other events besides the default Transfer and Approve and is therefore throwing an exception.

```   ErrorException 

  Undefined array key "0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c"

  at vendor/drlecks/simple-web3-php/Core/ABI.php:92
     88▕ 
     89▕ 
     90▕     public function GetEventFromHash($event_hash)
     91▕     {
  ➜  92▕         return $this->events_encoded[$event_hash];
     93▕     }
```

**Comment by drlecks** [comment]
Ok, I see the problem and we can add, for sure, the `!empty()` protection.

Just to be sure that I get it, this event hash you share `"0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c"` represents one of those non standard events, right? And you just want to skip them.
