### ISSUE TITLE
Custom blockchain ID

### ISSUE THREAD

**Issue by ooohmike** [drlecks/Simple-Web3-Php#59]
Is there any way to set custom Chain ID? I manually write like below but I don't see it's a good practice.
```$sweb3->chainId = 80001;```

I think we would need a setter function on `SWeb3.php` for chain ID.

**Comment by drlecks** [comment]
Hi,

Indeed this is the current way to set a custom chainId for sending signed transactions. As you can see in the [example.send.php](https://github.com/drlecks/Simple-Web3-Php/blob/master/Example/example.send.php) file.

Yes, it can be protected with Get/Set methods. But as it is not a "single direction attribute" (you can set it and read it externally), it is not so relevant... Maybe I'm missing something. Also, for back-compatibility reasons, it would break existing code bases by hiding this value behind a getter.
