### ISSUE TITLE
Get Balance

### ISSUE THREAD

**Issue by nash81** [drlecks/Simple-Web3-Php#6]
Hi,
Is there a method to get the balance of an address?
If we use the batch calls it gives the below error
$sweb3->call('eth_getBalance', [$sweb3->personal->address]);
Array ( [0] => stdClass Object ( [jsonrpc] => 2.0 [id] => 1 [error] => stdClass Object ( [code] => -32602 [message] => missing value for required argument 1 ) ) )

if we add 'latest'
$sweb3->call('eth_getBalance', [$sweb3->personal->address, 'latest']);
Response:
Array ( [0] => stdClass Object ( [jsonrpc] => 2.0 [id] => 1 [result] => 0x0 ) )

**Comment by drlecks** [comment]
Hi, I've just tested it and works on my workplace.

```PHP
$sweb3->batch(true);
$sweb3->call('eth_getBalance', [$sweb3->personal->address, 'latest']);
$res = $sweb3->executeBatch();
$balance = Utils::hexToBn($res[0]->result);    
echo $balance; 
$sweb3->batch(false);
```

Some things I would check:

- Does it work without the batch mode?
- Does `$sweb3->call('eth_blockNumber', []);` work as expected?
- Is Personal data is properly set `$sweb3->setPersonalData(SWP_ADDRESS, '');` before executing the call?
- Might be possible that the account you are requesting the balance has indeed 0 ether (0x0 means 0 balance)?

**Comment by nash81** [comment]
Thank you that worked, The balance in the account was indeed zero, I did try another account and got the value as BN
1498919699000000000
How do we convert it to the ETH balance display 1.498919699
I tried looking into the utils and could not find it.

**Comment by drlecks** [comment]
It's not straight-forward translating BN to string. I've added some functions in Utils to make the conversion easier.

Get average-human readable string representation from a value conversion:
```php  
$s_val = Utils::fromWeiToString('1001', 'kwei'); // "1.001"

$s_val = Utils::toWeiString('1.001', 'kwei'); // "1001"
```

**Comment by nash81** [comment]
Okay thank you, I also need some help in couple of other things, how can I get in touch with you offline other than github, if you have a email id?. Offcourse I will buy you a few coffees and cookies for it.

**Comment by drlecks** [comment]
This project has a gitter chat enabled for more direct communication. It would be a good place to share your doubts.

https://gitter.im/Simple-Web3-Php/community
