### ISSUE TITLE
Send USDT With Infura - Error with nonce in contract->send()

### ISSUE THREAD

**Issue by skykingisepic** [drlecks/Simple-Web3-Php#64]
PHP Fatal error:  Uncaught Exception: ERROR: estimateGas error: invalid argument 0: json: cannot unmarshal hex string "0x" into Go struct field TransactionArgs.nonce of type hexutil.Uint64 (-32602)

From the contract example:

$extra_data = [ 'nonce' => $sweb3->personal->getNonce() ];

This is returning zero (0), causing the contract->send to fail with the above error

$result = $contract->send('transfer', [$toAddress, $amount], $extra_data);

**Comment by ironistdmi** [comment]
$nonceBigInt = $this->sweb3->personal->getNonce();
        if ($nonceBigInt->compare(new \phpseclib\Math\BigInteger(0)) > 0) {
            $extra_data = ['nonce' => $nonceBigInt];
        } else {
            $nonceHex = '0x0';
            $extra_data = ['nonce' => $nonceHex];
        }
        
        use this, have same issue, solved with this code

**Comment by skykingisepic** [comment]
Resolved, thanks
