### ISSUE TITLE
How to estimate gas for contract method call

### ISSUE THREAD

**Issue by ebbbang** [drlecks/Simple-Web3-Php#8]
How can I estimate Gas for Contract Method Call?

**Comment by drlecks** [comment]
This is not an issue. You should ask questions through [gitter](https://gitter.im/Simple-Web3-Php/community). 

Some notes on your question: 
- Being strict, call methods don't cost gas, so you can't (or at least shouldn't) estimate gas for methods that don't change blockchian state (calls). Only "send" methods change blockchain state and have gas cost that can be estimated.
- You have a gas estimate example on the project [README](https://github.com/drlecks/Simple-Web3-Php#estimate--gas-price-from-send-params).
- [SWeb3_Contract](https://github.com/drlecks/Simple-Web3-Php/blob/master/Core/SWeb3_Contract.php) already populates gasLimit when calling `send()` if it's not present on the sent data. You can see there how to do it manually.
