### ISSUE TITLE
Add custom convert value

### ISSUE THREAD

**Issue by Sigri44** [drlecks/Simple-Web3-Php#9]
Hello,

Possibility to add a function to convert according to a precise value of decimals, useful in some cases, such as :

```php
function convertWithDecimals($result, $decimals) {
    // divide $result by $decimals
}
```

**Comment by drlecks** [comment]
Hi!

You can use the regular `Utils::fromWei()` / `Utils::toWei()` functions to achieve this behaviour.

Imagine that your token has 3 decimals. You only need to find the appropiate unit on the `Utils::UNITS` array.

```PHP
//convert a wei amount received from a contract call
$res = Utils::fromWeiToString('1000', 'kwei'); //res = '1' 

//convert a "human readable amount" to send as a contract method parameter
$res = Utils::toWeiString('1', 'kwei'); // res = '1000'
```

**Comment by Sigri44** [comment]
Hum my token has 8 decimals, and i can't use it with your example, it's not an nominative value.

**Comment by drlecks** [comment]
That's what happens when getting out of the mainstream! 😄

I'll add some functions to transform numbers by number of decimals! 👍

**Comment by Sigri44** [comment]
Ahahah most of my used contracts don't have the classic 18's standards or whatever.

PS : for the function it's :
`$result = $value / pow(10, $decimals);`

**Comment by drlecks** [comment]
Ok, my last commit should help you! I've added 3 functions in utils:

- toWeiFromDecimals()
- toWeiStringfromDecimals()
- fromWeiToDecimalsString()


Here is an example usecase:

```PHP
//convert a "human readable" input amount to wei applying 8 decimals
$res = Utils::toWeiFromDecimals('0.01', 8);  // (BigInteger) 1000000
var_dump($res->toString());

//convert a wei amount received from a contract call, apply decimals and return a human readable string
$res = Utils::fromWeiToDecimalsString('1000000', 8); //0.01 
var_dump($res);

//convert a "human readable" input amount to wei applying 3 decimals
//PS this should not be used in most scenarios, besides debugging.
$res = Utils::toWeiStringfromDecimals('1.001', 3); // 1001 
var_dump($res);
```
